image:
  repository: pjcyr/openstack-appcred
  tag: v1.1.9
restartPolicy: Never"
os_cloud: "mycloud"
appCred:
  name: "cicd_test"
  roles: "member,reader"
  expires_in: "none"
  description: "my cicd_test app cred test"
  unrestricted: "false"
  cluster_name: "my_secretname"
  if_exists: "fail"