image:
  repository: pjcyr/openstack-appcred
  tag: v1.1.6
os_cloud: 
appCred:
  name: "cicd_test"
  roles: "member,reader"
  expires_in: "none"
  description: "my cicd_test app cred test"
  unrestricted: "false"
  cluster_name: "my_secretname"