# rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appcreds-writer
  namespace: "${{ .Values.appCred.cluster_name }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appcreds-secret-writer
  namespace: "${{ .Values.appCred.cluster_name }}"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","create","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appcreds-secret-writer-binding
  namespace: "${{ .Values.appCred.cluster_name }}"
subjects:
  - kind: ServiceAccount
    name: appcreds-writer
    namespace: "${{ .Values.appCred.cluster_name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: appcreds-secret-writer